### ISSUE TITLE
Demo link?

### ISSUE THREAD

**Issue by oyeanuj** [maslianok/react-select-me#1]
Hi @maslianok! Thanks for open sourcing this component! Are you planning on putting out a demo so that users can see the component in action?

**Comment by maslianok** [comment]
@oyeanuj http://maslianok.github.io/react-select-me/

**Comment by oyeanuj** [comment]
Great, thanks! This is looking really good. I was wondering if you had any thoughts on how this compares to react-select, react-super-select or other such options? I imagine you probably looked at them, so it would be very helpful to get your perspective on this library vs those, for anyone making a choice.

Thank you!

**Comment by maslianok** [comment]
@oyeanuj  Well, the main idea is to keep the code as simple as possible and, as the result, very fast. The code doesn't contain the logic to fetch or to filter the data. And there is only one thing in the state - whether the list of options visible or not.

Everything is customizable. You can pass className for the every element. The API supports renderers for almost every piece of the component. So, if you can - you customize it with help of CSS, if not - use renderers and change default behaviour.

And, as a bonus, a lot of useful features, that I didn't have with other libraries: direction to open, ability to open programatically, expand list to the page boundaries to not brake your layout, support of immutable data etc.

And yes, I use it in production, so you also can :)
