### ISSUE TITLE
if options is an array of shape {value,label} and value is a primitive, the primitive is not mapped to its necessary value.

### ISSUE THREAD

**Issue by r3wt** [maslianok/react-select-me#10]
will submit pr if you will allow it. obviously this removes alot of unnecessary overhead in using this library.

**Comment by r3wt** [comment]
@maslianok hello, is this library being maintained?

**Comment by maslianok** [comment]
Hi @r3wt 
Thanks for your feedback!

Yes, this library is maintained. It would be awesome if you can help me and create a PR

**Comment by r3wt** [comment]
i can't even see where to begin with this library.

**Comment by maslianok** [comment]
Can you please provide a code snippet for the bug described above?

If I understood you correctly, you're trying to pass options as an array and the selected value as a primitive, right? 

For example:
```javascript
const options = [
  { value: 0, label: 'Value 0' },
  { value: 1, label: 'Value 1' },
];
// ...
<Select options={options} value={0} />
```

This code works properly for me.

**Comment by r3wt** [comment]
@maslianok yes that's right. it may be related to #12 which i reported. currently i'm doing something like this in the render method of my wrapper around Select:

```
var value = this.props.value;
if(typeof this.props.value !== 'object'){
    for(var i=0;i<this.props.options.length;i++){
        // eslint-disable-next-line
        if(this.props.options[i].value==this.props.value){
            value = this.props.options[i];
        }
    }
}
```
maybe when 1.0.1 ships it will be fixed, that's my hope anyway.

**Comment by maslianok** [comment]
This is too old and I hope it was resolved 2 years ago :)

I'm closing this now. Let me know if the bug still exists
