### ISSUE TITLE
when value === 0, nothing is selected

### ISSUE THREAD

**Issue by r3wt** [maslianok/react-select-me#12]
when value === 0, nothing is selected

example:

```
const options = [
{ value: 0, label: 'Test' }
];
<Select options={options} value={0} />
```
this results in nothing being selected.

additionally, it is not possible to select the item who's value is 0, however other options are selectable.

**Comment by maslianok** [comment]
Fixed in v.1.0.1

Thanks for catching this bug!

**Comment by r3wt** [comment]
@maslianok thank you sir. i appreciate.

**Comment by r3wt** [comment]
@maslianok how long until 1.0.1 can ship? i have a bug i'm in desperate need to fix...

**Comment by maslianok** [comment]
It's already there https://www.npmjs.com/package/react-select-me
