### ISSUE TITLE
Please remove lightweight from repository description

### ISSUE THREAD

**Issue by f1yn** [maslianok/react-select-me#13]
Since this library uses immutable.js (which sucks for treeshaking), having the label "lightweight" can cause confusion for developers expecting smaller build sizes with the packages.

### Build size without `react-select-me` (webpack 4 + uglifyjs, no styles):
```site.min.js  149 KiB       0  [emitted]  main```

### Build size with `react-select-me` (webpack 4 + uglifyjs, no styles):
```site.min.js  295 KiB       0  [emitted]  [big]  main```

**Comment by f1yn** [comment]
Or alternatively, mention that it uses immutable js more consciously. While I understand how this can be seen as lightweight for projects already using immutable, for light projects that don't already use it it creates a contradictory situation.

**Comment by maslianok** [comment]
yeah, I didn't see this problem... Thanks for catching this, @flynnham 

I want this library to be lightweight.

Do you see any solutions or should we get rid of ImmutableJS?

**Comment by maslianok** [comment]
Ok, so there are at least 2 problems:
- Immutable
- React-virtualized

<img width="1242" alt="screen shot 2018-08-07 at 10 56 23 am" src="https://user-images.githubusercontent.com/3485490/43762524-d7cfb96c-9a30-11e8-8580-fa55088d81d5.png">

I'm probably going to remove Immutable, and try to create a separate HOC for virtualized dropdowns...

**Comment by maslianok** [comment]
Ok, seems that I don't need to remove `lightweight` from the repository description :)

I extracted `immutable` and `virtualized` features into separate HOCs. Now the library size is only 4.25kb gzipped.

<img width="902" alt="screen shot 2018-08-07 at 11 59 34 am" src="https://user-images.githubusercontent.com/3485490/43767749-89c9dd5c-9a3e-11e8-9185-4ce938c2cad1.png">

Released in [v.1.0.0](https://github.com/maslianok/react-select-me/releases/tag/v.1.0.0)

**Comment by r3wt** [comment]
@maslianok thanks bud. for those of us who don't use immutable that helps immensely.
