### ISSUE TITLE
How do I check which CustomSelect was selected??

### ISSUE THREAD

**Issue by abhisheksoni27** [maslianok/react-select-me#16]
So, I have multiple Select's in a single parent component. Now, in the `onChange`, I only get the value selected but it has no information about which `CustomSelect` changed. How can I get that information, or how would you achieve the same without wrapping the Select into a separate component?

**Comment by abhisheksoni27** [comment]
:laughing: Resolved. Just added the name when calling `onChanged`. 

Anyway, Great lib!

**Comment by maslianok** [comment]
Thanks @abhisheksoni27 for your feedback,
I appreciate it!
