### ISSUE TITLE
'Searchable' search does not filter data

### ISSUE THREAD

**Issue by kchupakhin** [maslianok/react-select-me#18]
Hello, I faced with some problem.
I'm using this code:
`<SelectMe
        searchClearOnClose
        searchable
        onChange={handler}
        placeholder={placeholder}
        options={['red', 'green', 'blue']}
        value={value}
      />`

I've seen in live example, when we select props 'Searchable' also select automatically prop 'Clear search on close' and when we write some text in input we see realtime filtering by options. But when I tried code above the list of options did not change. What am I doing wrong?

**Comment by deronjohnson** [comment]
You need to provide an `onSearch` function to the component to filter the options being passed to it. The author has provided an example in the readme: https://github.com/maslianok/react-select-me#onsearch-function

**Comment by kchupakhin** [comment]
> You need to provide an `onSearch` function to the component to filter the options being passed to it. The author has provided an example in the readme: https://github.com/maslianok/react-select-me#onsearch-function

Yes, I did so at the moment)
I just thought that if I do not override the function, it will work by default, which would be convenient. I was a bit confused by example)

Thanks for answer.

**Comment by maslianok** [comment]
@deronjohnson Thanks for the answer 👍 

@kchupakhin `react-select-me` is a stateless component. It doesn't keep any filtered options in the inner state

**Comment by kchupakhin** [comment]
> @kchupakhin `react-select-me` is a stateless component. It doesn't keep any filtered options in the inner state

Yes, I already understood. Thanks!
