### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ReactSelectMe`.

### ISSUE THREAD

**Issue by jsmankoo** [maslianok/react-select-me#2]
This is the full error.
warning.js?8a56:36 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ReactSelectMe`. See https://fb.me/react-warning-keys for more information.

Its a very common react error as you know. I even put a key prop in my optionRenderer Component but it still gives me the error. The only time it didnt give me the error was when under listRenderer instead of using the optionRenderer function I used my optionRenderer Component directly instead. But then I lost all the onClick and onChange events which is obvious.

Was wondering If you could shed some light on why is this happening

**Comment by maslianok** [comment]
Sorry that I left you without answer for such a long time.

The library uses keys in 2 cases:
- to render options
- to render selected items (in case of multiple select)

It means that you must provide uniq keys inside `value` and `options` props.

For example:
```javascript
const options = [
  { value: 1, label: 'Label 1' },
  { value: 2, label: 'Label 2' },
]
```

You may also change key value:
`<Select valueKey="id" options={[{ id: 1, label: 'Label 1' }]}`
