### ISSUE TITLE
Tab index is broken

### ISSUE THREAD

**Issue by m-reyes-h** [maslianok/react-select-me#21]
There is a way to implement tab index to the component?

**Comment by maslianok** [comment]
Well, it's not a problem to add `tabIndex` prop to some element and to make it focusable.

But you probably want the component to be responsible for keyboard events, right? To toggle the list on enter, to select/unselect options by pressing up/down keys. And this is a huge task.

We already have an issue for the keyboard support https://github.com/maslianok/react-select-me/issues/9

Unfortunately, we don't have any volunteers to work on this...

In the meantime, you can use [`selectedBlockRenderer`](https://github.com/maslianok/react-select-me/tree/f454303cebbe32f32ee1d7232d41abc16b14d02c#selectedblockrenderer-function) to add your own logic. Or, of course, you can help the community, and create a MR for keyboard support.

**Comment by m-reyes-h** [comment]
There is a way to get access to the wrapper component? I would like to add tabindex="0" to the parent of all components. 
The method **selectedBlockRenderer** just let me manage the rendered block inside the wrapper, not the wrapper itself

**Comment by maslianok** [comment]
Can you provide a context of this problem? I'm not sure I understand why do you need to set `tabindex="0"` to the wrapper.

Can't you add a custom wrapper and add tabindex to it? e.g.
```
<div tabIndex="0">
  <Select ...
</div>
```

**Comment by m-reyes-h** [comment]
Of curse, I can do something like that, but I prefer to avoid an extra wrapper (div) and just apply tabindex to the Select.

I have some available time next week so, "you can help the community, and create a MR for keyboard support." Please tell me what is a MR and how can I improve the actual code?!

Regards

**Comment by maslianok** [comment]
@m-reyes-h thanks for your intention and willingness to help with this problem.

MR means "Merge Request". It comes from GitLab :) GitHub name is "Pull Request" - PR

There are many articles on how to create PR to open-source projects. For example, you can start with this one https://www.geeksforgeeks.org/making-first-open-source-pull-request/

The idea is that you clone the repo, make some changes and create a request to merge them into the main repo.

-----
Regarding changes: it would be great if the library will support at least some basic keyboard events, e.g.
- to be focusable by Tab key (tabIndex prop)
- to respond to Enter/Esc (open list on Enter and close on Esc)

Later on we can add up/down arrow to select a specific option.

**Comment by maslianok** [comment]
I would vote to close this issue and continue the discussion here https://github.com/maslianok/react-select-me/issues/9
