### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by vincent-vade** [maslianok/react-select-me#29]
Hi guys,

First awesome lightweight <Select /> without 500 props with useless use case =)

That could be better if we add @typed/react-select-me support ?
What do u think ?

Vincent

**Comment by maslianok** [comment]
Thanks for your feedback 👍 

I'm not an expert in TS, but I suppose it should be it easy to implement, right?

Something like "copy-paste" from [PropTypes](https://github.com/maslianok/react-select-me/blob/master/src/propsDefinitions.js#L44) to some specific file with a specific format at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo.

@vincent-vade do you know how it works? Can you help me with this?

**Comment by vincent-vade** [comment]
Hi,

@maslianok
Sorry for the delay of my response... Yes i will open a new PR about typescript support for the component. If it's ok for u ?

**Comment by maslianok** [comment]
sure!

Post a link to PR here, so I can approve it.

Thanks in advance! 💪
