### ISSUE TITLE
if value is set to null, it crashes

### ISSUE THREAD

**Issue by rogeriocsilva** [maslianok/react-select-me#34]
To clean an input I set my value to null, not undefined, and this results in a crash. I've read this [issue](https://github.com/maslianok/react-select-me/issues/14) and I'm forced to do the same in my Select wrapper: `value: value != null ? value : undefined`

``` TypeError: Cannot read property 'value' of null
ReactSelectMe._this.patchSelectedOption
node_modules/react-select-me/lib/ReactSelectMe.js:85
  82 | 
  83 | // search for this option in the `options` array
  84 | 
> 85 | var value = (typeof selectedOption === 'undefined' ? 'undefined' : _typeof(selectedOption)) === 'object' ? selectedOption[valueKey] : selectedOption;
     | ^  86 | var option = options.find(function (o) {
  87 |   return _this.getProp(o, valueKey) === value;
  88 | });```

**Comment by maslianok** [comment]
There are so many edge cases with `undefined/null` values...  
Some of them:
- `typeof null` returns an `object` in javascript. Of course, we may add additional conditions everywhere to handle null values but this conflicts with the next requirement
- some people want to add `null` options, e.g. a special option that has a `null` value. In addition to this, they want to be able to reset values. This sounds reasonable to me, so we have to distinguish `null` & `undefined` values

There are many other small problems with `undefined` vs `null`.

I hope the condition you added to your code doesn't cause any problems, so I'd vote to keep the existing logic inside the library.

Let me know if you have any thoughts on this or/and any questions/suggestions.

**Comment by maslianok** [comment]
I'm closing the issue. Happy to reopen if you have any additional thoughts or suggestions
