### ISSUE TITLE
Support for react 17

### ISSUE THREAD

**Issue by JulesPatry** [maslianok/react-select-me#36]
Can't install this amazing library right now on my app because it doesn't support react 17. 

I think upgrading the support for react 17 wouldn't be hard due to react 17 having few to none breaking changes.

Error while npm installing...
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.7 || ^15.0.0 || ^16.0.0" from react-select-me@1.3.0
npm ERR! node_modules/react-select-me
npm ERR!   react-select-me@"^1.3.0" from the root project

**Comment by maslianok** [comment]
Thanks for the feedback :)

Should be fixed in v1.3.1
