### ISSUE TITLE
Some issues I face in using properties

### ISSUE THREAD

**Issue by msman** [maslianok/react-select-me#6]
hi,
thank you for the great work!

I tried to use the value: Any , I put it like 
`value="1"` and `value="Any"`  both didn't work. Note that 1 means the value of first object in the options.
Whereas `isOpened="true"` worked.

**Comment by msman** [comment]
Now, got it, I set 
`		this.state = { 
			value: 1 
		};`

thank you and

**Comment by msman** [comment]
I couldn't apply the Icon renderer

I put this in my class
`iconRenderer(isOpened) {
  return <i className={isOpened ? 'icon-open' : 'icon-close'} />;
}`

but how to call it inside the <select />?

**Comment by msman** [comment]
Regarding the CSS, I followed the instructions and tried to edit the file `react-select-me/src/ReactSelectMe.css` but no effect. Also, tried  other way of building my own css  i.e `dd__wrapper: 'my-super-class'`, but also didn't work for me.

**Comment by maslianok** [comment]
> I couldn't apply the Icon renderer

```
iconRenderer() {
    return <i className="icon" />
  }
  render() {
    return (
      <Select iconRenderer={this.renderIcon} />
    );
  }
```


> Regarding the CSS

for CSS modules
```javascript
import defaultStyles from 'react-select-me/src/ReactSelectMe.css';
import s from './styles.css'
// ...

const selectStyles = {
  ...defaultStyles, // copy all default styles
  dd__selectedOption: s.mySuperSelectedOption, // but reassign styles for selectedOption
};
<Select s={s} {...otherProps} />
```

for usual css
```
import 'react-select-me/src/ReactSelectMe.css';
import './styles.css'

<Select />
```
